### ISSUE TITLE
[BUG] RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by behroozazarkhalili** [takuseno/d3rlpy#210]
**Describe the bug**
There is no straightforward method to empty the cuda cache or handle garbage collection. In addition, it is not clear how users can utilize more than one GPU simultaneously.

Tried to allocate 186.00 MiB (GPU 0; 9.78 GiB total capacity; 8.52 GiB already allocated; 95.19 MiB free; 8.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory, try setting max_split_size_mb to avoid fragmentation.

**To Reproduce**
It should be necessary to use the following method wherever required.
To reproduce the error, just run any code with a huge amount of data.
`
    gc.collect()
    torch.cuda.empty_cache()
`

**Expected behavior**
The library should develop methods for data cleaning from cuda.

**Comment by takuseno** [comment]
There is no need to clean up GPU cache in d3rlpy. Currently, d3rlpy does not support multi-GPU training. But, you can switch which GPU to use by specifying the device id so that you can run multi experiments at once by using different devices.
```
import d3rlpy
cql = d3rlpy.algos.CQL(use_gpu=1)  # device id=1
```

Please note that how much resources on GPU will be used depends on the data size of a single mini-batch and model sizes. The total amount of dataset does not matter here.

**Comment by behroozazarkhalili** [comment]
> There is no need to clean up GPU cache in d3rlpy. Currently, d3rlpy does not support multi-GPU training. But, you can switch which GPU to use by specifying the device id so that you can run multi experiments at once by using different devices.
> 
> ```
> import d3rlpy
> cql = d3rlpy.algos.CQL(use_gpu=1)  # device id=1
> ```
> 
> Please note that how much resources on GPU will be used depends on the data size of a single mini-batch and model sizes. The total amount of dataset does not matter here.

Thank you for your prompt response.
Regarding your comment and explanation, I should state that I set my `batch_size `to a very small number; however, it again raised a **CUDA out of memory error**.

**Comment by takuseno** [comment]
What's the shape of observation here? I believe this is not an issue of d3rlpy.

**Comment by behroozazarkhalili** [comment]
> What's the shape of observation here? I believe this is not an issue of d3rlpy.

Its shape is `[num_samples, 999]`; indeed, the feature size is 999.

**Comment by takuseno** [comment]
I confirmed this works on my environment (Geforce 1080ti) with less than 1GiB of GPU memory consumption.
```py
import d3rlpy
import numpy as np

observations = np.random.random((1000, 1000)).astype(np.float32)
actions = np.random.random((1000, 4)).astype(np.float32)
rewards = np.random.random(1000).astype(np.float32)
terminals = np.zeros(1000)
terminals[-1] = 1.0

dataset = d3rlpy.dataset.MDPDataset(observations, actions, rewards, terminals)
cql = d3rlpy.algos.CQL(batch_size=256, use_gpu=True)

cql.fit(dataset, n_steps=10000, n_steps_per_epoch=1000)
```

For further investigation, I need reproducible codes.

**Comment by takuseno** [comment]
Let me close this issue since it's not a reproducible issue. Feel free to reopen this if you still have this issue.
